public class AddressHandler{
    
         public string State;
         public string getState() { return State;}
         public void setState(string value) { State=value;}
    
         public string Line1;
         public string getLine1() { return Line1;}
         public void setLine1(string value) { Line1=value;}
    
         public string Line2;
         public string getLine2() { return Line2;}
         public void setLine2(string value) { Line2=value;}
    

}