/*
Author=String.Empty 
Date = 11/11/2017 12:00:00 AM
Lightning Enabled = False 
Template Description = String.Empty 
Last Action = String.Empty 
*/
public class AssetHandler{


        
         public string Productcode;
         public string getProductcode() { return Productcode;}
         public void setProductcode(string value) { Productcode=value;}
    
         public string Name;
         public string getName() { return Name;}
         public void setName(string value) { Name=value;}
    
    
    

}