/*
Author=String.Empty 
Date = 11/11/2017 12:00:00 AM
Lightning Enabled = False 
Template Description = String.Empty 
Last Action = String.Empty 
*/
public class ContractHandler{


        
         public date Startdate;
         public date getStartdate() { return Startdate;}
         public void setStartdate(date value) { Startdate=value;}
    
         public date Enddate;
         public date getEnddate() { return Enddate;}
         public void setEnddate(date value) { Enddate=value;}
    
    
    

}