/*
Author=New Author 
Date = 11/11/2017 12:00:00 AM
Lightning Enabled = True 
Template Description = Desc 
Last Action = New 
*/
public class Contract22Handler{


        
         public date Startdate;
         public date getStartdate() { return Startdate;}
         public void setStartdate(date value) { Startdate=value;}
    
         public date Enddate;
         public date getEnddate() { return Enddate;}
         public void setEnddate(date value) { Enddate=value;}

}