public with sharing class TestClassNew123 {
    
         public String Id;
         public String getId() { return Id;}
         public void setId(String value) { Id=value;}
    
         public String Isdeleted;
         public String getIsdeleted() { return Isdeleted;}
         public void setIsdeleted(String value) { Isdeleted=value;}
    
         public String Masterrecordid;
         public String getMasterrecordid() { return Masterrecordid;}
         public void setMasterrecordid(String value) { Masterrecordid=value;}
    
         public String Name;
         public String getName() { return Name;}
         public void setName(String value) { Name=value;}
    
         public String Type;
         public String getType() { return Type;}
         public void setType(String value) { Type=value;}
    
         public String Parentid;
         public String getParentid() { return Parentid;}
         public void setParentid(String value) { Parentid=value;}
    
         public String Billingstreet;
         public String getBillingstreet() { return Billingstreet;}
         public void setBillingstreet(String value) { Billingstreet=value;}
    
         public String Billingcity;
         public String getBillingcity() { return Billingcity;}
         public void setBillingcity(String value) { Billingcity=value;}
    
         public String Billingstate;
         public String getBillingstate() { return Billingstate;}
         public void setBillingstate(String value) { Billingstate=value;}
    
         public String Billingpostalcode;
         public String getBillingpostalcode() { return Billingpostalcode;}
         public void setBillingpostalcode(String value) { Billingpostalcode=value;}
    
         public String Billingcountry;
         public String getBillingcountry() { return Billingcountry;}
         public void setBillingcountry(String value) { Billingcountry=value;}
    
         public String Billinglatitude;
         public String getBillinglatitude() { return Billinglatitude;}
         public void setBillinglatitude(String value) { Billinglatitude=value;}
    
         public String Billinglongitude;
         public String getBillinglongitude() { return Billinglongitude;}
         public void setBillinglongitude(String value) { Billinglongitude=value;}
    
         public String Billinggeocodeaccuracy;
         public String getBillinggeocodeaccuracy() { return Billinggeocodeaccuracy;}
         public void setBillinggeocodeaccuracy(String value) { Billinggeocodeaccuracy=value;}
    
         public String Billingaddress;
         public String getBillingaddress() { return Billingaddress;}
         public void setBillingaddress(String value) { Billingaddress=value;}
    
         public String Shippingstreet;
         public String getShippingstreet() { return Shippingstreet;}
         public void setShippingstreet(String value) { Shippingstreet=value;}
    
         public String Shippingcity;
         public String getShippingcity() { return Shippingcity;}
         public void setShippingcity(String value) { Shippingcity=value;}
    
         public String Shippingstate;
         public String getShippingstate() { return Shippingstate;}
         public void setShippingstate(String value) { Shippingstate=value;}
    
         public String Shippingpostalcode;
         public String getShippingpostalcode() { return Shippingpostalcode;}
         public void setShippingpostalcode(String value) { Shippingpostalcode=value;}
    
         public String Shippingcountry;
         public String getShippingcountry() { return Shippingcountry;}
         public void setShippingcountry(String value) { Shippingcountry=value;}
    
         public String Shippinglatitude;
         public String getShippinglatitude() { return Shippinglatitude;}
         public void setShippinglatitude(String value) { Shippinglatitude=value;}
    
         public String Shippinglongitude;
         public String getShippinglongitude() { return Shippinglongitude;}
         public void setShippinglongitude(String value) { Shippinglongitude=value;}
    
         public String Shippinggeocodeaccuracy;
         public String getShippinggeocodeaccuracy() { return Shippinggeocodeaccuracy;}
         public void setShippinggeocodeaccuracy(String value) { Shippinggeocodeaccuracy=value;}
    
         public String Shippingaddress;
         public String getShippingaddress() { return Shippingaddress;}
         public void setShippingaddress(String value) { Shippingaddress=value;}
    
         public String Phone;
         public String getPhone() { return Phone;}
         public void setPhone(String value) { Phone=value;}
    
         public String Fax;
         public String getFax() { return Fax;}
         public void setFax(String value) { Fax=value;}
    
         public String Accountnumber;
         public String getAccountnumber() { return Accountnumber;}
         public void setAccountnumber(String value) { Accountnumber=value;}
    
         public String Website;
         public String getWebsite() { return Website;}
         public void setWebsite(String value) { Website=value;}
    
         public String Photourl;
         public String getPhotourl() { return Photourl;}
         public void setPhotourl(String value) { Photourl=value;}
    
         public String Sic;
         public String getSic() { return Sic;}
         public void setSic(String value) { Sic=value;}
    
         public String Industry;
         public String getIndustry() { return Industry;}
         public void setIndustry(String value) { Industry=value;}
    
         public Decimal Annualrevenue;
         public Decimal getAnnualrevenue() { return Annualrevenue;}
         public void setAnnualrevenue(Decimal value) { Annualrevenue=value;}
    
         public integer Numberofemployees;
         public integer getNumberofemployees() { return Numberofemployees;}
         public void setNumberofemployees(integer value) { Numberofemployees=value;}
    
         public String Ownership;
         public String getOwnership() { return Ownership;}
         public void setOwnership(String value) { Ownership=value;}
    
         public String Tickersymbol;
         public String getTickersymbol() { return Tickersymbol;}
         public void setTickersymbol(String value) { Tickersymbol=value;}
    
         public String Description;
         public String getDescription() { return Description;}
         public void setDescription(String value) { Description=value;}
    
         public String Rating;
         public String getRating() { return Rating;}
         public void setRating(String value) { Rating=value;}
    
         public String Site;
         public String getSite() { return Site;}
         public void setSite(String value) { Site=value;}
    
         public String Ownerid;
         public String getOwnerid() { return Ownerid;}
         public void setOwnerid(String value) { Ownerid=value;}
    
         public String Createddate;
         public String getCreateddate() { return Createddate;}
         public void setCreateddate(String value) { Createddate=value;}
    
         public String Createdbyid;
         public String getCreatedbyid() { return Createdbyid;}
         public void setCreatedbyid(String value) { Createdbyid=value;}
    
         public String Lastmodifieddate;
         public String getLastmodifieddate() { return Lastmodifieddate;}
         public void setLastmodifieddate(String value) { Lastmodifieddate=value;}
    
         public String Lastmodifiedbyid;
         public String getLastmodifiedbyid() { return Lastmodifiedbyid;}
         public void setLastmodifiedbyid(String value) { Lastmodifiedbyid=value;}
    
         public String Systemmodstamp;
         public String getSystemmodstamp() { return Systemmodstamp;}
         public void setSystemmodstamp(String value) { Systemmodstamp=value;}
    
         public String Lastactivitydate;
         public String getLastactivitydate() { return Lastactivitydate;}
         public void setLastactivitydate(String value) { Lastactivitydate=value;}
    
         public String Lastvieweddate;
         public String getLastvieweddate() { return Lastvieweddate;}
         public void setLastvieweddate(String value) { Lastvieweddate=value;}
    
         public String Lastreferenceddate;
         public String getLastreferenceddate() { return Lastreferenceddate;}
         public void setLastreferenceddate(String value) { Lastreferenceddate=value;}
    
         public String Jigsaw;
         public String getJigsaw() { return Jigsaw;}
         public void setJigsaw(String value) { Jigsaw=value;}
    
         public String Jigsawcompanyid;
         public String getJigsawcompanyid() { return Jigsawcompanyid;}
         public void setJigsawcompanyid(String value) { Jigsawcompanyid=value;}
    
         public String Cleanstatus;
         public String getCleanstatus() { return Cleanstatus;}
         public void setCleanstatus(String value) { Cleanstatus=value;}
    
         public String Accountsource;
         public String getAccountsource() { return Accountsource;}
         public void setAccountsource(String value) { Accountsource=value;}
    
         public String Dunsnumber;
         public String getDunsnumber() { return Dunsnumber;}
         public void setDunsnumber(String value) { Dunsnumber=value;}
    
         public String Tradestyle;
         public String getTradestyle() { return Tradestyle;}
         public void setTradestyle(String value) { Tradestyle=value;}
    
         public String Naicscode;
         public String getNaicscode() { return Naicscode;}
         public void setNaicscode(String value) { Naicscode=value;}
    
         public String Naicsdesc;
         public String getNaicsdesc() { return Naicsdesc;}
         public void setNaicsdesc(String value) { Naicsdesc=value;}
    
         public String Yearstarted;
         public String getYearstarted() { return Yearstarted;}
         public void setYearstarted(String value) { Yearstarted=value;}
    
         public String Sicdesc;
         public String getSicdesc() { return Sicdesc;}
         public void setSicdesc(String value) { Sicdesc=value;}
    
         public String Dandbcompanyid;
         public String getDandbcompanyid() { return Dandbcompanyid;}
         public void setDandbcompanyid(String value) { Dandbcompanyid=value;}
    
         public String Customerpriority;
         public String getCustomerpriority() { return Customerpriority;}
         public void setCustomerpriority(String value) { Customerpriority=value;}
    
         public String SLA;
         public String getSLA() { return SLA;}
         public void setSLA(String value) { SLA=value;}
    
         public String Active;
         public String getActive() { return Active;}
         public void setActive(String value) { Active=value;}
    
         public String Numberoflocations;
         public String getNumberoflocations() { return Numberoflocations;}
         public void setNumberoflocations(String value) { Numberoflocations=value;}
    
         public String Upsellopportunity;
         public String getUpsellopportunity() { return Upsellopportunity;}
         public void setUpsellopportunity(String value) { Upsellopportunity=value;}
    
         public String Slaserialnumber;
         public String getSlaserialnumber() { return Slaserialnumber;}
         public void setSlaserialnumber(String value) { Slaserialnumber=value;}
    
         public String Slaexpirationdate;
         public String getSlaexpirationdate() { return Slaexpirationdate;}
         public void setSlaexpirationdate(String value) { Slaexpirationdate=value;}
    
    
    public Account accStdRecord             {get; set;}
    
    public TestClassNew123( ApexPages.StandardController stdController ){
        try {
            accStdRecord = (Account) stdController.getRecord();
            if(accStdRecord.Id != null)
            {
            String query = AccessControlUtility.getViewableFieldsQuery( Account.getSObjectType(), accStdRecord.Id );
            accStdRecord = Database.query( query );
            }
            List<Schema.SObjectField> viewableFields = AccessControlUtility.getViewableFields( Account.getSObjectType() );
            if( !AccessControlUtility.isAuthorizedToView( Account.getSObjectType(), new List<Schema.SObjectField>() ) ){
                accStdRecord = null;
                ApexPages.addMessage(new ApexPages.Message( ApexPages.severity.error, 'Access Control violation: Not authorized to view.' ));
            }
        }catch (Exception e ) {
            ApexPages.addMessage(new ApexPages.Message( ApexPages.severity.error, 'Access Control violation: '+e.getMessage() ));
        }
    }
    
    public void insertRecord( ){
        try {
            List<Schema.SObjectField> cretableFields = AccessControlUtility.getCreatableFields( Account.getSObjectType() );
            
            if( AccessControlUtility.isAuthorizedToCreate( Account.getSObjectType(), cretableFields ) ){
                accStdRecord = (Account) AccessControlUtility.insertAsUser( accStdRecord, cretableFields );
            }else{
                ApexPages.addMessage(new ApexPages.Message( ApexPages.severity.error, 'Access Control violation: Not authorized to insert.' ));
            }
        }catch (Exception e ) {
            ApexPages.addMessage(new ApexPages.Message( ApexPages.severity.error, 'Access Control violation: '+e.getMessage() ));
        }
    }
    
    public void updateRecord( ){
        try {
            List<Schema.SObjectField> updatebleFields = AccessControlUtility.getUpdateableFields( Account.getSObjectType() );
            
            if( AccessControlUtility.isAuthorizedToUpdate( Account.getSObjectType(), updatebleFields ) ){
                accStdRecord = (Account) AccessControlUtility.updateAsUser( accStdRecord, updatebleFields );
            }else{
                ApexPages.addMessage(new ApexPages.Message( ApexPages.severity.error, 'Access Control violation: Not authorized to update.' ));
            }
        }catch (Exception e ) {
            ApexPages.addMessage(new ApexPages.Message( ApexPages.severity.error, 'Access Control violation: '+e.getMessage() ));
        }
    }
    
    
}